export const SHUFFLED_QUOTES = [
  "You do not rise to the level of your goals. You fall to the level of your systems.",
  "Atomic habits compound over time. Small, consistent improvements yield massive results.",
  "Quality is not an act, it is a habit. You are what you repeatedly do.",
  "The secret of your future is hidden in your daily routine.",
  "We first make our habits, and then our habits make us.",
  "Discipline is choosing between what you want now and what you want most.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "It is easier to prevent bad habits than to break them.",
  "The smallest steps are still progress.",
  "Consistency is the true foundation of virtue.",
  "Be not afraid of going slowly, be afraid only of standing still.",
  "A river cuts through rock, not because of its power, but because of its persistence.",
  "Great things are done by a series of small things brought together.",
  "Your habits will determine your future. Choose them with care.",
  "Energy and persistence conquer all things.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "Focus on the process, not the outcome. The results will follow.",
  "Daily discipline is the bridge between goals and accomplishment.",
  "The hard part isn't getting your body in shape. The hard part is getting your mind in shape.",
  "Small daily improvements over time lead to stunning results.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Continuous improvement is better than delayed perfection.",
  "You will never change your life until you change something you do daily.",
  "Patience, persistence and perspiration make an unbeatable combination.",
  "Action is the foundational key to all success.",
  "Habit is a cable; we weave a thread of it each day, and at last we cannot break it.",
  "The chains of habit are too weak to be felt until they are too strong to be broken.",
  "Well begun is half done.",
  "Do not let what you cannot do interfere with what you can do.",
  "Start where you are. Use what you have. Do what you can.",
  "Success isn't always about greatness. It's about consistency.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "To create more positive results in your life, focus on your habits.",
  "Don't wish it were easier. Wish you were better.",
  "If you are going through hell, keep going.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "If you can dream it, you can do it.",
  "Believe you can and you're halfway there.",
  "It always seems impossible until it's done.",
  "Our greatest weakness lies in giving up.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Do one thing every day that scares you.",
  "The only place where success comes before work is in the dictionary.",
  "Your life does not get better by chance, it gets better by change.",
  "You miss 100% of the shots you don't take.",
  "Hard work beats talent when talent doesn't work hard.",
  "The path to success is to take massive, determined action.",
  "If you want to build a new habit, make it obvious, attractive, easy, and satisfying.",
  "Habits are the compound interest of self-improvement.",
  "The ultimate form of intrinsic motivation is when a habit becomes part of your identity.",
  "The most effective way to change your habits is to focus not on what you want to achieve, but on who you wish to become.",
  "Every action you take is a vote for the type of person you wish to become.",
  "Real change comes from the compound effect of hundreds of small decisions.",
  "Missing once is an accident. Missing twice is the start of a new bad habit.",
  "One of the best ways to build a new habit is to stack it onto an existing one.",
  "The secret to building lasting habits is to start incredibly small.",
  "Focus on the identity you want to build, and let the habits support it.",
  "Do not break the chain. Settle for less volume, but maintain the habit.",
  "An environment designed for success makes good habits friction-free.",
  "Reduce friction for good habits, increase friction for bad ones.",
  "Choose habits that match your natural talents and inclination.",
  "Success is a system, not a single event.",
  "A habit must be established before it can be improved.",
  "Standardize before you optimize.",
  "Focus on progress, not perfection.",
  "Repetition is the mother of learning, and the father of habit.",
  "Your daily routines are a mirror of your self-respect.",
  "Small steps taken every single day add up to miles over a lifetime.",
  "Discipline is the soul of an army. It makes small numbers formidable.",
  "Mastering others is strength. Mastering yourself is true power.",
  "Self-control is strength. Right thought is mastery. Calmness is power.",
  "If you want to win, you must first control yourself.",
  "Your focus determines your reality.",
  "What you focus on grows, what you feed dies.",
  "Keep your face always toward the sunshine, and shadows will fall behind you.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Try to be a rainbow in someone's cloud.",
  "Nothing is impossible. The word itself says 'I'm possible!'",
  "The best way to predict the future is to create it.",
  "Change your thoughts and you change your world.",
  "Light tomorrow with today.",
  "Believe that you can, and you are already halfway there.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "The power of concentration is the key to all power.",
  "Energy flows where attention goes.",
  "Decide what you want, decide what you are willing to exchange for it, and get to work.",
  "It is never too late to be what you might have been.",
  "The limit of your always-active mind is your only boundary.",
  "The secret of getting ahead is getting started.",
  "You cannot cross the sea merely by standing and staring at the water.",
  "Look for the good in every day, and build habits that multiply it.",
  "Make each day your masterpiece.",
  "Don't count the days, make the days count.",
  "If you change the way you look at things, the things you look at change.",
  "Everything has beauty, but not everyone sees it.",
  "Be yourself; everyone else is already taken.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "Go confidently in the direction of your dreams. Live the life you've imagined.",
  "If you don't design your own life plan, chances are you'll fall into someone else's.",
  "Either you run the day or the day runs you.",
  "Productivity is never an accident. It is always the result of a commitment to excellence.",
  "The best preparation for tomorrow is doing your best today.",
  "You cannot escape the responsibility of tomorrow by evading it today.",
  "Do not wait for the perfect moment. Take the moment and make it perfect.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Yesterday is history, tomorrow is a mystery, today is a gift.",
  "If you want to lift yourself up, lift up someone else.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Growth is the only evidence of life.",
  "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
  "Courage is grace under pressure.",
  "The only way to do great work is to love what you do.",
  "Do not take life too seriously. You will never get out of it alive.",
  "Happiness is not something readymade. It comes from your own actions.",
  "Out of difficulties grow miracles.",
  "We must embrace pain and burn it as fuel for our journey.",
  "You can, you should, and if you're brave enough to start, you will.",
  "Defeat is not bitter unless you swallow it.",
  "Turn your wounds into wisdom.",
  "Write it on your heart that every day is the best day in the year.",
  "Act as if what you do makes a difference. It does.",
  "If you want to conquer fear, don't sit home and think about it. Go out and get busy.",
  "The journey of a thousand miles begins with one step.",
  "Perseverance is not a long race; it is many short races one after another.",
  "Nothing will work unless you do.",
  "The key is not to prioritize what's on your schedule, but to schedule your priorities.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "Focus on being productive instead of busy.",
  "Your time is limited, don't waste it living someone else's life.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "Live life to the fullest, and focus on the positive.",
  "Small practices lead to great mastery over time.",
  "Consistency beats talent every single day.",
  "When you feel like quitting, remember why you started.",
  "Do something today that your future self will thank you for.",
  "Success is not in what you have, but in who you have become.",
  "The only bad workout is the one that didn't happen.",
  "Your potential is endless. Go do what you were created to do.",
  "Make consistency your superpower.",
  "Do not let yesterday take up too much of today.",
  "No matter how hard the past is, you can always begin again.",
  "Dream big. Start small. Act now.",
  "Be patient with yourself. Self-growth is tender; it's holy ground.",
  "It is in your moments of decision that your destiny is shaped.",
  "A year from now you may wish you had started today.",
  "Live the habits of the person you want to become today.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "What we do today is what matters most."
];
